if not vim.g.vscode then
	require("plugins")
	require("colorscheme")
	require("treesitter")
	require("lsp")
	require("cmps")
	require("git")
	require("lualines")
	require("nvim-trees")
	require("toggleterms")
	require("alphas")
	require("projects")
	require("whichkey")
	require("flash_config")
	require("trouble_config")
	require("fidget")
	require("noice_config")
end

require("options")
require("keymaps")
require("indentline")
